// package testpkg is generated from schema.avsc
package testpkg

// Code generated by avro/gen. DO NOT EDIT.

// Test is a test struct
type Test struct {
	// SomeString is a string
	SomeString string `avro:"someString"`
	SomeInt    int    `avro:"someInt"`
}
