// Code generated by avro/gen. DO NOT EDIT.
package testpkg

import (
	"encoding/json"

	"github.com/google/uuid"
)

// Test is a test struct.
type Test struct {
	// SomeString is a uuid.
	SomeString uuid.UUID `avro:"someString"`
	// SomeBytes is actually a json raw message.
	SomeBytes json.RawMessage `avro:"someBytes"`
	// SomeInt is actually just an int32.
	SomeInt int32 `avro:"someInt"`
}
