package testpkg

// Code generated by avro/gen. DO NOT EDIT.

import (
	"github.com/hamba/avro/v2"
)

// Test is a generated struct.
type Test struct {
	SomeString string `avro:"someString"`

	schema avro.Schema
}

// Schema returns the schema for Test.
func (o *Test) Schema() avro.Schema {
	if o.schema == nil {
		o.schema = avro.MustParse(`{"name":"a.b.test","type":"record","fields":[{"name":"someString","type":"string"}]}`)
	}
	return o.schema
}

// Unmarshal decodes b into the receiver.
func (o *Test) Unmarshal(b []byte) error {
	return avro.Unmarshal(o.Schema(), b, o)
}

// Marshal encodes the receiver.
func (o *Test) Marshal() ([]byte, error) {
	return avro.Marshal(o.schema, o)
}
