package testpkg

// Code generated by avro/gen. DO NOT EDIT MANUALLY.

// Test is a test struct
type ABTest struct {
	// SomeString is a string
	SomeString string `avro:"someString"`
	SomeInt    int    `avro:"someInt"`
}
